name: Metrics
on:
  # Schedule daily updates (every 24 hours)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run it manually from the Actions tab
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: nipuna-lakruwan
          template: classic
          base: ""
          config_timezone: Asia/Colombo
          
          # This is the Magic Part: "Repositories" Plugin
          plugin_repositories: yes
          plugin_repositories_order: pushed # Sort by latest pushed code
          plugin_repositories_featured: weather-sentinel # Force this one to stay (optional)
          plugin_repositories_pinned: 0 # Ignore pinned, just show latest
          plugin_repositories_limit: 4 # Show top 4 latest repos
