name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Run manually
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "Update metrics"
          committer_branch: main
          committer_gist: false

          # Options
          user: nipuna-lakruwan
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Colombo
          config_output: default
          
          # Activity Plugin
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          
          # Languages Plugin
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          
          # Notable Contributions
          plugin_notable: yes
          plugin_notable_filter: stars:>50
          
          # Repositories Plugin: Show latest pushed code
          plugin_repositories: yes
          plugin_repositories_order: pushed
          plugin_repositories_pinned: 0
          plugin_repositories_limit: 4
